### ISSUE TITLE
copypedeps suggestions

### ISSUE THREAD

**Issue by 3oheicrw** [brechtsanders/pedeps#10]
Assumed I compiled a simple C++ program by mingw64 and I have mingw64/bin added to Windows PATH (all of the needed DLLs are also there too). If I run `copypedeps program.exe` (without specifying target dir as it's assumed to be the current dir), copypedeps should be able to copy all of the needed DLLs from mingw64/bin to the current dir (the same dir as program.exe).

**Comment by 3oheicrw** [comment]
@brechtsanders

**Comment by brechtsanders** [comment]
The destination folder is mandatory.

In my opnion your suggestion could be dangerous if people start accidentally overwriting files in the current directory when they just forget to specify a destination folder.

Instead use `.` for the local folder, like this: `copypedeps program.exe .`
