### ISSUE TITLE
`-i` and `-e` switches

### ISSUE THREAD

**Issue by ghost** [brechtsanders/pedeps#13]
> > Do you mean you want command options to only get output like this?
> > 
> > ```
> > architecture: x86_64
> > machine name: AMD AMD64 (x64)
> > subsystem:    Windows console
> > DLL:          no
> > stripped:     yes
> > file version: 0.0
> > minimum Windows version: 5.2
> > ```
> 
> I consider this to be the standard information about the binary. But I don't want to view both `IMPORTS` and `EXPORTS` at the same time. There should be option switches to display only `IMPORTS` (e.g: `-i`?) or `EXPORTS` (e.g: `-e`?).

_Originally posted by @mh466lfa in https://github.com/skeeto/w64devkit/issues/168#issuecomment-2337227440_

**Comment by brechtsanders** [comment]
I prefer to use `-x` instead of `-e` for exports.

This is what it looks like now:
```raw
listpedeps -h
Usage: listpedeps [-h|-?] [-v] [-n] [-i] [-s] [-x] srcfile [...]
Parameters:
  -h -?         display command line help
  -v            display version and exit
  -n            don't show file info
  -i            list imports
  -s            short import list without symbols
  -x            list exports
Description:
  Lists dependencies of .exe and .dll files.
Version: 0.1.14 (library version: 0.1.14)
```
