### ISSUE TITLE
virustotal report failure

### ISSUE THREAD

**Issue by lygstate** [brechtsanders/pedeps#7]
https://www.virustotal.com/gui/file-analysis/NjM4OWFkYmFlODcwYmIwNWYzMmJmYWVkOWNhYWNkM2E6MTYzNjEyNTIwMQ==

**Comment by brechtsanders** [comment]
This is a library and tools accessing the inners of .exe and .dll files, so I'm not surprised it will get false positives.
I'm not sure what can be done about that though.
