### ISSUE TITLE
listpedeps missed libwinpthread-1.dll

### ISSUE THREAD

**Issue by 3oheicrw** [brechtsanders/pedeps#9]
Assume I have a simple C++ program compiled by mingw64. It successfully listed libgcc_s_seh-1.dll and libstdc++-6.dll but it missed libwinpthread-1.dll so the program doesn't run.

**Comment by 3oheicrw** [comment]
@brechtsanders

**Comment by brechtsanders** [comment]
`copypedeps` can only copy files it finds in the `PATH` environment variable.
Did you run `listpedeps`/`copypedeps` while `PATH` was pointing to the location of `libwinpthread-1.dll`?

**Comment by 3oheicrw** [comment]
> `copypedeps` can only copy files it finds in the `PATH` environment variable. Did you run `listpedeps`/`copypedeps` while `PATH` was pointing to the location of `libwinpthread-1.dll`?

`libwinpthread-1.dll` is in the same location as other dlls. MSYS2's `ldd` doesn't miss `libwinpthread-1.dll`

**Comment by brechtsanders** [comment]
Was this maybe a dependency of a dependency? If so you need to add the `-r` flag.

**Comment by 3oheicrw** [comment]
> **Was this maybe a dependency of a dependency?** If so you need to add the `-r` flag.

Seems to be so.
